version: '3.3'

services:

  # PHP Service
  php:
    build: './php/'
    container_name: laravel-php
    networks:
      - backend
    volumes:
      - ./public_html/racketServiceWeb:/var/www/html/
      - ./apache2/log:/var/log/apache2

  # Apache Service
  apache:
    build: './apache2/'
    container_name: laravel-apache
    depends_on:
      - php
      - pgsql
    networks:
      - frontend
      - backend
    ports:
      - "8080:80"
      - "443:443"
    volumes:
      - ./public_html/racketServiceWeb:/var/www/html
      - ./apache2/log:/var/log/apache2

  #PostgreSQL Service
  pgsql:
    image: postgres:12.0-alpine
    container_name: laravel-pgsql
    working_dir: /data/pgsql
    volumes:
    - ./postgresql-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres1
      POSTGRES_DB: racketservice
    ports:
      - 5432:5432
    networks:
      - backend

networks:
  frontend:
  backend: